apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rpi-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: rpi-exporter
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rpi-exporter
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rpi-exporter
        app.kubernetes.io/component: exporter
        app.kubernetes.io/part-of: monitoring
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9110"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: rpi-exporter
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: rpi-exporter
          image: ghcr.io/cha0s-corp/rpi-exporter:latest
          imagePullPolicy: Always
          args:
            - "-addr=:9110"
            - "-sensehat"
          ports:
            - containerPort: 9110
              name: metrics
              protocol: TCP
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
            requests:
              memory: "32Mi"
              cpu: "50m"
          securityContext:
            privileged: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: vcio
              mountPath: /dev/vcio
              readOnly: true
            - name: i2c
              mountPath: /dev/i2c-1
              readOnly: true
      volumes:
        - name: vcio
          hostPath:
            path: /dev/vcio
            type: CharDevice
        - name: i2c
          hostPath:
            path: /dev/i2c-1
            type: CharDevice
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/arch: arm64
      terminationGracePeriodSeconds: 30
      priorityClassName: system-node-critical
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rpi-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: rpi-exporter
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: rpi-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: rpi-exporter
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: monitoring
spec:
  selector:
    app.kubernetes.io/name: rpi-exporter
  ports:
    - name: metrics
      port: 9110
      targetPort: metrics
      protocol: TCP
  clusterIP: None
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rpi-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: rpi-exporter
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rpi-exporter
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - monitoring
